In [8]:
import numpy as np

In [9]:
x = np.array([[1, 0, 0], [-2, 1, 0], [-6, 0, 1]])
y = np.array([[1, 2, 3], [2, 5, 2], [6, -3, 1]])
z = np.matmul(x, y)
print(z)

[[  1   2   3]
 [  0   1  -4]
 [  0 -15 -17]]


In [10]:
x = np.array([[1, 0, 0], [0, 1, 0], [0, 15, 1]])
y = np.array([[1, 2, 3], [0, 1, -4], [0, -15, -17]])
z = np.matmul(x, y)
print(z)

[[  1   2   3]
 [  0   1  -4]
 [  0   0 -77]]


In [11]:
x = np.array([[1, 0, 0], [0, 1, 0], [0, 15, 1]])
y = np.array([[1, 0, 0], [-2, 1, 0], [-6, 0, 1]])
z = np.matmul(x, y)
print(z)

[[  1   0   0]
 [ -2   1   0]
 [-36  15   1]]


In [12]:
x = np.array([[1, 0, 0], [-2, 1, 0], [-36, 15, 1]])
y = np.array([[1, 2, 3], [2, 5, 2], [6, -3, 1]])
z = np.matmul(x, y)
print(z)

[[  1   2   3]
 [  0   1  -4]
 [  0   0 -77]]
